name: 'Accuknox Opengrep Scan'
description: 'Perform OpenGrep scan on your repository and upload the results to Accuknox'

inputs:
  REPOSITORY_URL:
    description: 'Repository URL'
    required: false
  COMMIT_SHA:
    description: 'Commit SHA'
    required: false
  COMMIT_REF:
    description: 'Commit Reference'
    required: false
  PIPELINE_ID:
    description: 'Github Run ID'
    required: true
    default: '${{ github.run_id }}'
  JOB_URL:
    description: 'Github Job URL'
    required: true
    default: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
  ACCUKNOX_ENDPOINT:
    description: 'The URL of the CSPM panel to push the scan results to'
    required: true
    default: 'cspm.dev.accuknox.com'
  ACCUKNOX_TENANT:
    description: 'The ID of the tenant associated with the CSPM panel.'
    required: true
  ACCUKNOX_TOKEN:
    description: 'The token for authenticating with the CSPM panel.'
    required: true
  ACCUKNOX_LABEL:
    description: 'The label created in AccuKnox SaaS for associating scan results.'
    required: true
  INPUT_SOFT_FAIL:
    description: 'Do not return an error code if there are failed checks.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Run OpenGrep
      shell: bash
      run: |
        set +e
        docker run --rm -v "$PWD:/app" \
          -e REPOSITORY_URL="${{ inputs.REPOSITORY_URL }}" \
          -e COMMIT_SHA="${{ inputs.COMMIT_SHA }}" \
          -e COMMIT_REF="${{ inputs.COMMIT_REF }}" \
          -e PIPELINE_ID="${{ inputs.PIPELINE_ID }}" \
          -e JOB_URL="${{ inputs.JOB_URL }}" \
          safeeraccuknox/demo:opengreptest-1.7
        echo "OPENGREP_EXIT_CODE=$?" >> $GITHUB_ENV

    - name: Push report to CSPM panel
      shell: bash
      run: |
        set +e
        cat results.json | jq
        curl --silent --show-error --fail --location \
          --request POST "https://${{ inputs.ACCUKNOX_ENDPOINT }}/api/v1/artifact/?tenant_id=${{ inputs.ACCUKNOX_TENANT }}&data_type=SG&label_id=${{ inputs.ACCUKNOX_LABEL }}&save_to_s3=true" \
          --header "Tenant-Id: ${{ inputs.ACCUKNOX_TENANT }}" \
          --header "Authorization: Bearer ${{ inputs.ACCUKNOX_TOKEN }}" \
          --form 'file=@"results.json"'
        echo "AK_EXIT_CODE=$?" >> $GITHUB_ENV

    - name: Fail pipeline if scan fails
      shell: bash
      run: |
        FINAL_EXIT_CODE=0

        if [ "$OPENGREP_EXIT_CODE" -ne 0 ] || [ "$AK_EXIT_CODE" -ne 0 ]; then
          FINAL_EXIT_CODE=$OPENGREP_EXIT_CODE
          if [ "$OPENGREP_EXIT_CODE" -eq 0 ]; then
            FINAL_EXIT_CODE=$AK_EXIT_CODE
          fi
        fi

        echo "FINAL_EXIT_CODE=$FINAL_EXIT_CODE"

        if [ "$FINAL_EXIT_CODE" -ne 0 ]; then
          if [ "${{ inputs.INPUT_SOFT_FAIL }}" = "true" ]; then
            echo "Scan failed, but soft fail is enabled. Continuing..."
          else
            echo "Scan failed and soft fail is disabled. Exiting with failure."
            exit 1
          fi
        else
          echo "Scan completed successfully."
        fi