name: 'Accuknox Opengrep Scan'
description: 'Perform OpenGrep scan on your repository and upload the results to Accuknox'
author: "Accuknox"

branding:  
  icon: "activity"  
  color: "blue"   

inputs:
  repository_url:
    description: 'Repository URL'
    required: false
  commit_sha:
    description: 'Commit SHA'
    required: false
  commit_ref:
    description: 'Commit Reference'
    required: false
  pipeline_id:
    description: 'Github Run ID'
    required: true
    default: '${{ github.run_id }}'
  job_url:
    description: 'Github Job URL'
    required: true
    default: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
  accuknox_endpoint:
    description: 'The URL of the CSPM panel to push the scan results to'
    required: true
    default: 'cspm.dev.accuknox.com'
  accuknox_tenant:
    description: 'The ID of the tenant associated with the CSPM panel.'
    required: true
  accuknox_token:
    description: 'The token for authenticating with the CSPM panel.'
    required: true
  accuknox_label:
    description: 'The label created in AccuKnox SaaS for associating scan results.'
    required: true
  input_soft_fail:
    description: 'Do not return an error code if there are failed checks.'
    required: false
    default: 'false'
  upload_artifact:
    description: 'Upload the scan results as a GitHub artifact'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Run OpenGrep
      shell: bash
      run: |
        set +e
        docker run --rm -v "$PWD:/app" \
          -e REPOSITORY_URL="${{ inputs.repository_url }}" \
          -e COMMIT_SHA="${{ inputs.commit_sha }}" \
          -e COMMIT_REF="${{ inputs.commit_ref }}" \
          -e PIPELINE_ID="${{ inputs.pipeline_id }}" \
          -e JOB_URL="${{ inputs.job_url }}" \
          safeeraccuknox/demo:opengreptest-1.7
        echo "OPENGREP_EXIT_CODE=$?" >> $GITHUB_ENV

    - name: Push report to CSPM panel
      shell: bash
      run: |
        set +e
        curl --silent --show-error --fail --location \
          --request POST "https://${{ inputs.accuknox_endpoint }}/api/v1/artifact/?tenant_id=${{ inputs.accuknox_tenant }}&data_type=SG&label_id=${{ inputs.accuknox_label }}&save_to_s3=true" \
          --header "Tenant-Id: ${{ inputs.accuknox_tenant }}" \
          --header "Authorization: Bearer ${{ inputs.accuknox_token }}" \
          --form 'file=@"results.json"'
        echo "AK_EXIT_CODE=$?" >> $GITHUB_ENV

    - name: Upload Scan Results as Artifact
      if: inputs.upload_artifact == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: scan-results-${{ github.sha }}
        path: results.json
        if-no-files-found: ignore

    - name: Fail pipeline if scan fails
      shell: bash
      run: |
        FINAL_EXIT_CODE=0

        if [ "$OPENGREP_EXIT_CODE" -ne 0 ] || [ "$AK_EXIT_CODE" -ne 0 ]; then
          FINAL_EXIT_CODE=$OPENGREP_EXIT_CODE
          if [ "$OPENGREP_EXIT_CODE" -eq 0 ]; then
            FINAL_EXIT_CODE=$AK_EXIT_CODE
          fi
        fi

        echo "FINAL_EXIT_CODE=$FINAL_EXIT_CODE"

        if [ "$FINAL_EXIT_CODE" -ne 0 ]; then
          if [ "${{ inputs.input_soft_fail }}" = "true" ]; then
            echo "Scan failed, but soft fail is enabled. Continuing..."
          else
            echo "Scan failed and soft fail is disabled. Exiting with failure."
            exit 1
          fi
        else
          echo "Scan completed successfully."
        fi